# Generated by Django 3.0.5 on 2021-01-11 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('components', '0002_auto_20210111_1137'),
        ('recipes', '0003_auto_20210111_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChooseItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_quantity', models.FloatField()),
                ('item_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_name', to='components.Food')),
                ('item_quantity_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_quantity_unit', to='components.MeasuringUnit')),
            ],
        ),
        migrations.CreateModel(
            name='GroceryList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(max_length=40)),
                ('list_items', models.ManyToManyField(blank=True, null=True, related_name='items_list', to='groceries.ChooseItem')),
                ('list_recipes', models.ManyToManyField(blank=True, null=True, related_name='recipe_list', to='recipes.Recipe')),
            ],
        ),
    ]
