# Generated by Django 3.0.5 on 2023-03-29 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes', '0001_initial'),
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChooseItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_quantity', models.FloatField()),
                ('item_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_name', to='components.Food')),
            ],
        ),
        migrations.CreateModel(
            name='GroceryList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='GroceryListItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choose_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groceries.ChooseItem')),
                ('grocery_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groceries.GroceryList')),
            ],
        ),
        migrations.AddField(
            model_name='grocerylist',
            name='list_items',
            field=models.ManyToManyField(blank=True, related_name='items_list', through='groceries.GroceryListItems', to='groceries.ChooseItem'),
        ),
        migrations.AddField(
            model_name='grocerylist',
            name='list_recipes',
            field=models.ManyToManyField(blank=True, related_name='recipe_list', to='recipes.Recipe'),
        ),
    ]
