# Generated by Django 3.0.5 on 2023-03-31 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chooseitem',
            name='item_quantity_unit',
            field=models.CharField(default='other', max_length=20),
        ),
    ]
