# Generated by Django 3.0.5 on 2021-01-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20210111_1137'),
        ('groceries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocerylist',
            name='list_items',
            field=models.ManyToManyField(blank=True, related_name='items_list', to='groceries.ChooseItem'),
        ),
        migrations.AlterField(
            model_name='grocerylist',
            name='list_recipes',
            field=models.ManyToManyField(blank=True, related_name='recipe_list', to='recipes.Recipe'),
        ),
    ]
