# Generated by Django 3.0.5 on 2023-03-31 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0002_chooseitem_item_quantity_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chooseitem',
            name='item_quantity_unit',
            field=models.CharField(choices=[('teaspoon(s)', 'teaspoon(s)'), ('TABLESPOON(s)', 'TABLESPOON(s)'), ('cup(s)', 'cup(s)'), ('pint(s)', 'pint(s)'), ('quart(s)', 'quart(s)'), ('gallon(s)', 'gallon(s)'), ('ounce(s)', 'ounce(s)'), ('pound(s)', 'pound(s)'), ('vegetable or fruit', 'vegetable or fruit'), ('other', 'other')], default='other', max_length=20),
        ),
    ]
