# Generated by Django 3.0.5 on 2021-06-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0002_auto_20210111_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocerylist',
            name='list_name',
            field=models.DateField(),
        ),
    ]
