# Generated by Django 3.0.5 on 2023-04-11 17:46

import app_components.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_components', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodAisle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aisle_in_store', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_aisle', to='app_components.Aisle')),
                ('food_name_for_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_name_for_store', to='app_components.Food')),
            ],
        ),
        migrations.CreateModel(
            name='GroceryStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=100)),
                ('store_address', models.CharField(max_length=200)),
                ('food_aisle_relationship', models.ManyToManyField(blank=True, related_name='food_aisle_relationship', to='app_stores.FoodAisle')),
            ],
        ),
    ]
