# Generated by Django 3.0.5 on 2020-12-21 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=100)),
                ('recipe_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('recipe_instructions', models.TextField(blank=True, null=True)),
                ('location_page_number', models.IntegerField(blank=True, null=True)),
                ('recipe_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_category', to='components.RecipeCategory')),
                ('recipe_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_location', to='components.RecipeBook')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_quantity', models.FloatField()),
                ('ingredient_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_name', to='components.Food')),
                ('linked_recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_recipe', to='recipes.Recipe')),
                ('quantity_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantity_unit', to='components.MeasuringUnit')),
            ],
        ),
    ]
