# Generated by Django 3.0.5 on 2020-12-22 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='linked_recipe',
            field=models.CharField(max_length=100),
        ),
    ]
