# Generated by Django 3.0.5 on 2023-03-31 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='quantity_unit',
            field=models.CharField(choices=[('teaspoon(s)', 'teaspoon(s)'), ('TABLESPOON(s)', 'TABLESPOON(s)'), ('cup(s)', 'cup(s)'), ('pint(s)', 'pint(s)'), ('quart(s)', 'quart(s)'), ('gallon(s)', 'gallon(s)'), ('ounce(s)', 'ounce(s)'), ('pound(s)', 'pound(s)'), ('vegetable or fruit', 'vegetable or fruit'), ('other', 'other')], max_length=20),
        ),
    ]
