# Generated by Django 3.0.5 on 2021-07-31 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20210715_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=5),
        ),
    ]
