# Generated by Django 3.0.5 on 2021-07-31 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20210731_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_rating',
            field=models.CharField(choices=[('bad', "Don't make this again"), ('okay', 'Not bad'), ('good', 'Pretty good'), ('best', 'Excellent')], default='good', max_length=20),
        ),
    ]
