# Generated by Django 3.0.5 on 2021-07-31 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20210731_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_rating',
            field=models.CharField(blank=True, choices=[('bad', "Don't make this again"), ('okay', 'Not bad'), ('good', 'Pretty good'), ('best', 'Excellent')], default='good', max_length=20, null=True),
        ),
    ]
