# Generated by Django 3.0.5 on 2021-08-03 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_auto_20210802_1719'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['ingredient_name']},
        ),
    ]
