# Generated by Django 3.0.5 on 2021-08-15 18:08

from django.db import migrations, models
import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_auto_20210803_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_name',
            field=models.CharField(max_length=100, validators=[recipes.models.recipe_de_dup_validation]),
        ),
    ]
