# Generated by Django 3.0.5 on 2021-01-11 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'ordering': ['food_aisle']},
        ),
        migrations.AlterField(
            model_name='food',
            name='food_aisle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_aisle', to='components.Aisle'),
        ),
    ]
