# Generated by Django 3.0.5 on 2021-07-28 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0002_auto_20210111_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipebook',
            name='recipe_book_image',
            field=models.ImageField(blank=True, default='default_book.jpg', null=True, upload_to='recipe_book_pics/'),
        ),
    ]
