# Generated by Django 3.0.5 on 2021-08-02 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0003_recipebook_recipe_book_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipebook',
            options={'ordering': ['book_name']},
        ),
    ]
