# Generated by Django 3.0.5 on 2021-08-02 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0004_auto_20210802_1603'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'ordering': ['food_name']},
        ),
    ]
