# Generated by Django 3.0.5 on 2021-08-03 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0006_auto_20210803_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='food_aisle',
        ),
    ]
