# Generated by Django 3.0.5 on 2021-08-03 14:03

import components.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0007_remove_food_food_aisle'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='food_aisle',
            field=models.ForeignKey(blank=True, default=components.models.Aisle.get_default_pk, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_aisle', to='components.Aisle'),
        ),
    ]
